server:
  port: 8181

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/registrationdb

azure:
  servicebus:
    connection-string: YOUR_SERVICE_BUS_CONNECTION_STRING
    queue-name: user-registration-queue

notifications:
  enabled: false