name: Trigger auto deployment for spring-backend-api

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/spring-backend-api-AutoDeployTrigger-28a2896d-1616-4150-9fe2-b07f96c211a6.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Give Gradle wrapper permission to execute
        run: chmod +x ./gradlew
      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPRINGBACKENDAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPRINGBACKENDAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPRINGBACKENDAPI_AZURE_SUBSCRIPTION_ID }}


      - name: Build and deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          imageToBuild: nishitaacr.azurecr.io/spring-backend-api:38de9ea1b4785f72ba3af7e9c8ba198f2e04e640
          registryUrl: nishitaacr.azurecr.io
          registryUsername: ${{ secrets.SPRINGBACKENDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPRINGBACKENDAPI_REGISTRY_PASSWORD }}
          containerAppName: spring-backend-api
          resourceGroup: TestResource
          targetPort: 8181
          environmentVariables: |
            mongo-uri=secretref:mongo-uri
